config/routes.rb
TicketPanda::Application.routes.draw do
  resources :events

  devise_for :admins
  devise_for :users 
  resources :users, :only =>[:show]
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/users/:id', to: 'users#show', via: 'get'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

 #validations for username field since it is not covered by Devise.
  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, 
  			format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }
  			
 # Virtual attribute for authenticating by either username or email
 # This is in addition to a real persisted field like 'username'. More like a transient variable
   attr_accessor :login

   # lower(username) used so that username is the same as UserName (case insensitive)
   def self.find_first_by_auth_conditions(warden_conditions)
   	conditions = warden_conditions.dup
   	if login = conditions.delete(:login)
   		where(conditions).where(["lower(username) = :value OR lower(email) = lower(:value)", { :value => login }]).first
   	else
   	    where(conditions).first
   	    end
   	end
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true
	validates :from_time, presence: true 
	validates :to_time, presence: true
	validates :user_id, presence: true, numericality: true
	validate :greater_than_from_time, :cannot_be_in_past => :from_time,
	 :cannot_be_in_past => :to_time


	def greater_than_from_time
		if from_time>to_time
			errors.add(:to_time, "can't be earlier than From Time")
		end
	end

	def cannot_be_in_past date
		if date.present? && date< Date.today
			errors.add(:date, "can't be in the past")
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Associations
  has_many :events, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  #validations for username field since it is not covered by Devise.
  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, 
  			format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'. More like a transient variable
   attr_accessor :login

  # lower(username) used so that username is the same as UserName (case insensitive)
   def self.find_first_by_auth_conditions(warden_conditions)
   	conditions = warden_conditions.dup
   	if login = conditions.delete(:login)
   		where(conditions).where(["lower(username) = :value OR lower(email) = lower(:value)", { :value => login }]).first
   	else
   	    where(conditions).first
   	    end
   	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  # before_filter :authenticate_admin!, :except => [:show]

  # GET /events
  # GET /events.json
  def index
    # @events = Event.all
    @events = Event.paginate(page: params[:page], per_page: 10).order('from_time DESC')
    respond_to do |format|
  format.html
  format.js
end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :from_time, :to_time, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "TicketPanda"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-warning alert-dismissable"> <button type="button"
    class="close" data-dismiss="alert" aria-hidden="true">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
       <tr>
        <td><%= link_to event.title, event %></td>
        <td><%= event.from_time %></td>
        <td><%= event.to_time %></td>
        <td><%= link_to event.user.username, event.user %></td>
        <!-- <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :from_time %><br>
    <%= f.datetime_select :from_time %>
  </div>
  <div class="field">
    <%= f.label :to_time %><br>
    <%= f.datetime_select :to_time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>All events</h1>
<!-- <br> -->

<%#= link_to 'New Event', new_event_path %>

<%= will_paginate %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>From time</th>
      <th>To time</th>
      <th>User</th>
    </tr>
  </thead>
<tbody>
    <%= render @events %>
  </tbody>

</table>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>From time:</strong>
  <%= @event.from_time %>
</p>

<p>
  <strong>To time:</strong>
  <%= @event.to_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    TicketPanda
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TicketPanda", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li ><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          
          <% if user_signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user.username), :class => 'navbar-link' %></li>
              <li><%= link_to "Settings", edit_user_registration_path, :class => 'navbar-link' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
              </li>
            </ul>
          </li>
          
          <% elsif admin_signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_admin_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Settings", '#', :class => 'navbar-link' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: 'navbar-link' %>
              </li>
            </ul>
          </li>
          <% else %>
          <li>
            <button type="button" class="btn btn-default navbar-btn">
              <%= link_to "Sign in", new_user_session_path %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-default navbar-btn">
              <%= link_to "Sign up", new_user_registration_path, id: "headerSignup" %>
            </button>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
    <%= render 'layouts/messages' %>	
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
 	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  This is the about us page.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact us.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on using this app.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to TicketPanda</h1>

  <h2>
    This is the home page for this application.
  </h2>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>